name: Auto Cherry-Pick from Upstream

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to create the PR against"
        required: true
        default: "main"
      use_private_packages:
        description: "Use private packages?"
        required: false
        type: boolean

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  audit-fix:
    uses: step-security/reusable-workflows/.github/workflows/auto_cherry_pick.yaml@fix_UpStream-Changes-Cherry-Pick
    with:
      original-owner: "lukka"
      repo-name: "run-vcpkg"
      base_branch: ${{ inputs.base_branch }}
      use_private_packages: true